(function(a){a.fn.extend({maskPassword:function(c){return this.each(function(){var h=function(){g.data("masked")?(g.html(pfund.mask_passwd),d.hide(),e.show(),d.val(e.val()),g.data("masked",!1)):(g.html(pfund.unmask_passwd),e.hide(),d.show(),e.val(d.val()),g.data("masked",!0));return!1},d=function(c){var c=a(c),d=a("<input type='password' />");d.insertAfter(c).attr({id:c.attr("id")+"_mask","class":c.attr("class"),style:c.attr("style")});d.hide();return d}(this),e=a(this),g=a(c);g.toggle(h,h);e.keyup(function(){d.val(e.val())});
d.keyup(function(){e.val(d.val())})})}})})(jQuery);
jQuery(function(a){function c(b){b.type!="dialogclose"&&a(this).dialog("close");a.validationEngine.closePrompt(".formError",!0)}function h(){document.location.href=a("#pfund-login-link").attr("href")}function d(){a("#pfund-wait-dialog").dialog("close");a.validationEngine.buildPrompt("#pfund-register-email",pfund.register_fail,"error")}function e(b){b.success?(a("#pfund-user-login").val(a("#pfund-register-username").val()),a("#pfund-user-pass").val(a("#pfund-register-pass").val()),a("#pfund-login-form").submit()):
(a("#pfund-wait-dialog").dialog("close"),b.errors?(b.errors.invalid_email&&a.validationEngine.buildPrompt("#pfund-register-email",pfund.invalid_email,"error"),b.errors.email_exists&&a.validationEngine.buildPrompt("#pfund-register-email",pfund.email_exists,"error"),b.errors.username_exists&&a.validationEngine.buildPrompt("#pfund-register-username",pfund.username_exists,"error"),b.errors.registerfail&&d()):d())}function g(){var b=a("#pfund-create-account-form");b.validationEngine({returnIsValid:!0,
scroll:!1})&&(a("#pfund-wait-dialog").html(pfund.reg_wait_msg),m(),b.ajaxSubmit({dataType:"json",success:e,error:d}))}function l(){a("#pfund-update-dialog").dialog("close");a("#pfund-register-dialog").dialog({modal:!0,width:300,resizable:!1,buttons:[{text:pfund.register_btn,click:g},{text:pfund.cancel_btn,click:c}],zIndex:99999});a("#pfund-register-pass").maskPassword("#pfund-mask-pass")}function m(){a("#pfund-wait-dialog").dialog({closeOnEscape:!1,draggable:!1,modal:!0,resizable:!1,zIndex:99999})}
function n(b,c,d){if(d.url.indexOf("validate-slug")>-1&&(b=a("."+b.data.errId),(b.length==0||!b.hasClass("ajaxed"))&&j))a(".ui-dialog").dialog().dialog("close"),a("#pfund-form").data("dirty",!1),m(),document.pfund_form.submit()}a.validationEngineLanguage={allRules:pfund.validation_rules};var i=a("#pfund-campaign-id");if(i.length>0)a.validationEngineLanguage.allRules.pfundSlug.extraData=i.val();var j=!1,k={modal:!0,resizable:!1,close:c,width:600,buttons:[{text:pfund.ok_btn,click:function(){a(".pfund-camp-locationformError").hasClass("ajaxed")&&
a(".pfund-camp-locationformError").removeClass("ajaxed");var b=a("#pfund-form");a(document).unbind("ajaxSuccess");a(document).bind("ajaxSuccess",{errId:"pfund-camp-locationformError"},n);j=b.validationEngine({scroll:!1,returnIsValid:!0})}},{text:pfund.cancel_btn,click:c}],zIndex:99999};a("#pfund-form input").change(function(){j=!1;a("#pfund-form").data("dirty",!0)});a("#pfund-add-dialog").dialog(k);a(".pfund-edit-btn").click(function(){var b=a("#pfund-edit-dialog");b.length>0?b.dialog(k):a("#pfund-add-dialog").dialog(k)});
pfund.date_format?a(".pfund-date").datepicker({dateFormat:pfund.date_format}):a(".pfund-date").datepicker();var i=[],f="";a("#pfund-login-link").length==1?(f=h,pfund.login_fn&&(f=window[pfund.login_fn]),i.push({text:pfund.login_btn,id:"pfund-login-btn",click:f}),a("#pfund-register-link").length==1&&(f=l,pfund.register_fn&&(f=window[pfund.register_fn]),i.push({text:pfund.register_btn,id:"pfund-register-btn",click:f})),f=pfund.continue_editing_btn):f=pfund.ok_btn;i.push({text:f,click:c});a("#pfund-update-dialog").dialog({modal:!0,
resizable:!1,buttons:i,zIndex:99999});a("#pfund-register-link").click(l);window.onbeforeunload=function(b){if(a("#pfund-form").data("dirty")){var b=b||window.event,c=pfund.save_warning;if(b)b.returnValue=c;return c}}});function pfund_validate_required_file(){var a,c,h=jQuery("input[class*='requiredFile']");for(c=0;c<h.length;c++)if(a=jQuery(h[c]),h[c].value===""&&!a.data("pfundFileSet"))return!1;return!0};
