(function(a){a.fn.extend({maskPassword:function(c){return this.each(function(){var h=function(){g.data("masked")?(g.html(bnfund.mask_passwd),d.hide(),e.show(),d.val(e.val()),g.data("masked",!1)):(g.html(bnfund.unmask_passwd),e.hide(),d.show(),e.val(d.val()),g.data("masked",!0));return!1},d=function(c){var c=a(c),d=a("<input type='password' />");d.insertAfter(c).attr({id:c.attr("id")+"_mask","class":c.attr("class"),style:c.attr("style")});d.hide();return d}(this),e=a(this),g=a(c);g.toggle(h,h);e.keyup(function(){d.val(e.val())});
d.keyup(function(){e.val(d.val())})})}})})(jQuery);
jQuery(function(a){function c(b){b.type!="dialogclose"&&a(this).dialog("close");a.validationEngine.closePrompt(".formError",!0)}function h(){document.location.href=a("#bnfund-login-link").attr("href")}function d(){a("#bnfund-wait-dialog").dialog("close");a.validationEngine.buildPrompt("#bnfund-register-email",bnfund.register_fail,"error")}function e(b){b.success?(a("#bnfund-user-login").val(a("#bnfund-register-username").val()),a("#bnfund-user-pass").val(a("#bnfund-register-pass").val()),a("#bnfund-login-form").submit()):
(a("#bnfund-wait-dialog").dialog("close"),b.errors?(b.errors.invalid_email&&a.validationEngine.buildPrompt("#bnfund-register-email",bnfund.invalid_email,"error"),b.errors.email_exists&&a.validationEngine.buildPrompt("#bnfund-register-email",bnfund.email_exists,"error"),b.errors.username_exists&&a.validationEngine.buildPrompt("#bnfund-register-username",bnfund.username_exists,"error"),b.errors.registerfail&&d()):d())}function g(){var b=a("#bnfund-create-account-form");b.validationEngine({returnIsValid:!0,
scroll:!1})&&(a("#bnfund-wait-dialog").html(bnfund.reg_wait_msg),m(),b.ajaxSubmit({dataType:"json",success:e,error:d}))}function l(){a("#bnfund-update-dialog").dialog("close");a("#bnfund-register-dialog").dialog({modal:!0,width:300,resizable:!1,buttons:[{text:bnfund.register_btn,click:g},{text:bnfund.cancel_btn,click:c}],zIndex:99999});a("#bnfund-register-pass").maskPassword("#bnfund-mask-pass")}function m(){a("#bnfund-wait-dialog").dialog({closeOnEscape:!1,draggable:!1,modal:!0,resizable:!1,zIndex:99999})}
function n(b,c,d){if(d.url.indexOf("validate-slug")>-1&&(b=a("."+b.data.errId),(b.length==0||!b.hasClass("ajaxed"))&&j))a(".ui-dialog").dialog().dialog("close"),a("#bnfund-form").data("dirty",!1),m(),document.bnfund_form.submit()}a.validationEngineLanguage={allRules:bnfund.validation_rules};var i=a("#bnfund-campaign-id");if(i.length>0)a.validationEngineLanguage.allRules.bnfundSlug.extraData=i.val();var j=!1,k={modal:!0,resizable:!1,close:c,width:600,buttons:[{text:bnfund.ok_btn,click:function(){a(".bnfund-camp-locationformError").hasClass("ajaxed")&&
a(".bnfund-camp-locationformError").removeClass("ajaxed");var b=a("#bnfund-form");a(document).unbind("ajaxSuccess");a(document).bind("ajaxSuccess",{errId:"bnfund-camp-locationformError"},n);j=b.validationEngine({scroll:!1,returnIsValid:!0})}},{text:bnfund.cancel_btn,click:c}],zIndex:99999};a("#bnfund-form input").change(function(){j=!1;a("#bnfund-form").data("dirty",!0)});a("#bnfund-add-dialog").dialog(k);a(".bnfund-edit-btn").click(function(){var b=a("#bnfund-edit-dialog");b.length>0?b.dialog(k):a("#bnfund-add-dialog").dialog(k)});
bnfund.date_format?a(".bnfund-date").datepicker({dateFormat:bnfund.date_format}):a(".bnfund-date").datepicker();var i=[],f="";a("#bnfund-login-link").length==1?(f=h,bnfund.login_fn&&(f=window[bnfund.login_fn]),i.push({text:bnfund.login_btn,id:"bnfund-login-btn",click:f}),a("#bnfund-register-link").length==1&&(f=l,bnfund.register_fn&&(f=window[bnfund.register_fn]),i.push({text:bnfund.register_btn,id:"bnfund-register-btn",click:f})),f=bnfund.continue_editing_btn):f=bnfund.ok_btn;i.push({text:f,click:c});a("#bnfund-update-dialog").dialog({modal:!0,
resizable:!1,buttons:i,zIndex:99999});a("#bnfund-register-link").click(l);window.onbeforeunload=function(b){if(a("#bnfund-form").data("dirty")){var b=b||window.event,c=bnfund.save_warning;if(b)b.returnValue=c;return c}}});function bnfund_validate_required_file(){var a,c,h=jQuery("input[class*='requiredFile']");for(c=0;c<h.length;c++)if(a=jQuery(h[c]),h[c].value===""&&!a.data("bnfundFileSet"))return!1;return!0};
